baseURL = "https://sangatberguna.pages.dev"
languageCode = "en-us"
title = "NgadGuna Blog"
theme = "papermod"
#enableRobotsTXT = true


[outputs]
  home = ["HTML", "RSS", "SITEMAP", "JSON"]

[params]
  enableSearch = true
  author = "Fatih Epep"
  description = "Blog tentang Arduino, Raspberry Pi, dan project kreatif lainnya."
  ShowImageInList = true
  ShowImageInSummary = true

[[params.socialIcons]]	
	name = "github"
	url = "https://github.com/gegesteorngoding"

[[params.socialIcons]]	
	name = "stackoverflow"
	url = "https://stackoverflow.com/users/24836627/gegesteor-ball"

[taxonomies]
  tag = "tags"
  category = "categories"
[menu]
	[[menu.main]]
	identifier = "home"
	name = "Home"
	url = "/"
	weight = 0

        [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags"
        weight = 0

[params.homeInfoParams]
	Title = "Halo para manusia diluar sana!"
	Content = "Disini gw bakal share semua project, pengetahuan, dan kegabutan gw. Have Fun >//<"
[markup.goldmark.renderer]
	unsafe = true








